//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int id { get; set; }
        public int idReceiver { get; set; }
        public int idSender { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string ReceiptPerson { get; set; }
        public Nullable<int> isPaid { get; set; }
        public Nullable<int> isReceived { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
