//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryReport
    {
        public int id { get; set; }
        public int idPublisher { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryPerson { get; set; }
        public string UnitLeader { get; set; }
    
        public virtual Publisher Publisher { get; set; }
    }
}
