//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPMSDatabase : DbContext
    {
        public BPMSDatabase()
            : base("name=BPMSDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Accountant> Accountants { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<DeliveryReport> DeliveryReports { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<ReceiptReport> ReceiptReports { get; set; }
    }
}
