//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptReport
    {
        public int id { get; set; }
        public int idAgency { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string ReceiptPerson { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
